"""empty message

Revision ID: 1ae108e58524
Revises: cd8f7e1172c8
Create Date: 2025-11-17 07:00:57.473134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae108e58524'
down_revision = 'cd8f7e1172c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onchain_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_column('onchain_id')

    # ### end Alembic commands ###
