"""empty message

Revision ID: 224443096552
Revises: a3cd7233dfe0
Create Date: 2025-11-17 08:10:37.673532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224443096552'
down_revision = 'a3cd7233dfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onchain_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_column('onchain_id')

    # ### end Alembic commands ###
