"""empty message

Revision ID: 780d90da95bd
Revises: 22c08d3b01f2
Create Date: 2025-11-16 06:19:06.831936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780d90da95bd'
down_revision = '22c08d3b01f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('super_admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elections')
    # ### end Alembic commands ###
