"""empty message

Revision ID: 79efcd180ecc
Revises: 2312d3ef44f9
Create Date: 2025-11-17 04:31:44.598481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79efcd180ecc'
down_revision = '2312d3ef44f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutional_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('institutional_records_registration_number_key'), type_='unique')
        batch_op.create_unique_constraint('uq_institutional_record_registration_election', ['registration_number', 'election_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutional_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_institutional_record_registration_election', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('institutional_records_registration_number_key'), ['registration_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
